// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Persistence;
using ToDoApp.Repository;

namespace ToDoApp.Repository.Migrations
{
    [DbContext(typeof(ToDoDataContext))]
    [Migration("20190522181459_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoApp.Entity.Entities.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CompletedDate");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a7dcb98-6a91-463d-8667-d66bc7d31e56"),
                            CreatedDate = new DateTime(2019, 5, 22, 18, 14, 59, 201, DateTimeKind.Utc).AddTicks(224),
                            Description = "Do it!",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("792b8742-e4da-41ef-a045-2d487daa0cba"),
                            CreatedDate = new DateTime(2019, 5, 22, 18, 14, 59, 201, DateTimeKind.Utc).AddTicks(2768),
                            Description = "Finish project",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b6b2b8ee-6d12-4929-bbb5-8b83ff38fcfe"),
                            CreatedDate = new DateTime(2019, 5, 22, 18, 14, 59, 201, DateTimeKind.Utc).AddTicks(2807),
                            Description = "Go to work!",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
